remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
minima:
  skin: dark
title: "a_cat.on(⌨️)"
description: Random blog for madonuko
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "posts"
